### ISSUE TITLE
Normal desktop navbar

### ISSUE THREAD

**Issue by resyfer** [codadept/decoding-apocalypse#53]
![image](https://user-images.githubusercontent.com/74897008/125801703-72232f3c-9ea3-43e8-a6f5-d90248e35088.png)

**Comment by resyfer** [comment]
https://decoding-apocalypse.herokuapp.com/doctors/2d67287b-ee83-43f2-b474-0b5f9725c73e

Isme merge conflict resolve nahi kia hai

**Comment by Sayahnneeta** [comment]
Abhi pura ready nahi hai😢ruk jaa thora
